baseURL = "https://textbooks.cs.ksu.edu/cis642-643"
languageCode = "en-us"
title = "K-State CIS 642/643 Textbook"
canonifyURLs = true
enableGitInfo = true

# Change the default theme to be use when building the site with Hugo
theme = ["hugo-theme-relearn"]

# For search functionality
[outputs]
  home = ["HTML", "RSS", "PRINT", "JSON"]
  section = ["HTML", "RSS", "PRINT", "TELE", "EMBED"]
  page = ["HTML", "RSS", "PRINT", "TELE", "EMBED"]

[params]
  alwaysopen = false
  textbookURL = "https://textbooks.cs.ksu.edu/cis642-643"
  editURL = "https://gitlab.cs.ksu.edu/nhbean/ksucs-hugo/tree/master/cis642-643-textbook/"
  author = "Nathan Bean"
  description = "K-State CIS 642/643 Textbook"
  showVisitedLinks = false
  disableSearch = false 
  disableSeoHiddenPages = true 
  disableTagHiddenPages = true
  disableAssetBusting = true
  disableInlineCopyToClipboard = true
  disableShortcutsTitle = false 
  disableLandingPageButton = true 
  disableLanguageSwitchingButton = false
  disableBreadcrumbs = false
  disableToc = false 
  disableMathJax = true 
  disableMermaid = true 
  disableSwagger = true 
  disableNextPrev = false 
  themeVariant = ["light-theme", "dark-theme"]
  collapsibleMenu = true 
  additionalContentLanguage = ["en"]

  #landingPageURL = "/cis642-643"
  #textbookURL = "https://textbooks.cs.ksu.edu/cis642-643"
  
  linenumbers = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[markup]
  [markup.highlight]
    # if set to `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT mermaid code fences will not work anymore! So this is a mandatory
    # setting for your site
    guessSyntax = false
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
